**mnul.prg
replace all zit with 0,z2it with 0,oit with 0,pit with 0,uit with 0
replace all zg1 with 0,zg2 with 0,zg3 with 0,zg4 with 0
replace all z2g1 with 0,z2g2 with 0,z2g3 with 0,z2g4 with 0
replace all og1 with 0,og2 with 0,og3 with 0,og4 with 0
replace all pg1 with 0,pg2 with 0,pg3 with 0,pg4 with 0
replace all ug1 with 0,ug2 with 0,ug3 with 0,ug4 with 0
replace all prihod with 0,cena with 0,prihodg with 0,cenag with 0
replace all summaob with 0
replace all itog with 0
replace all pprih with 0,pcen with 0
replace all prv with 0
return

