do case
 case month(data)=1
  mesac='ŸH‚€œ'
 case month(data)=2
  mesac='”…‚€‹œ'
 case month(data)=3
  mesac='Œ€’'
 case month(data)=4
  mesac='€…‹œ'
 case month(data)=5
  mesac='Œ€‰'
 case month(data)=6
  mesac='ˆHœ'
 case month(data)=7
  mesac='ˆ‹œ'
 case month(data)=8
  mesac='€‚ƒ“‘’'
 case month(data)=9
  mesac='‘…H’Ÿœ'
 case month(data)=10
  mesac='Š’Ÿœ'
 case month(data)=11
  mesac='HŸœ'
 case month(data)=12
  mesac='„…Š€œ'
endcase
return


