**zamen.prg
go top
replace all p with b->p,c with b->c,q1 with b->q1,c1 with b->c1
replace all q2 with b->q2,c2 with b->c2,q3 with b->q3,c3 with b->c3
replace all pg with b->pg,cg with b->cg,q1g with b->q1g,c1g with b->c1g
replace all q2g with b->q2g,c2g with b->c2g,q3g with b->q3g,c3g with b->c3g
replace all ost with b->ost,sua with b->sua

replace all prihod with b->prihod,cena with b->cena         
replace all prihodg with b->prihodg,cenag with b->cenag
replace all mesprih with b->mesprih,messum with b->messum
replace all mespg with b->mespg,messg with b->messg
replace all xg1 with b->xg1,xg2 with b->xg2,xg3 with b->xg3,xg4 with b->xg4
replace all sxg1 with b->sxg1,sxg2 with b->sxg2,sxg3 with b->sxg3
replace all sxg4 with b->sxg4

replace all mespn with b->mespn,messn with b->messn
replace all orspr with b->orspr,orssup with b->orssup
replace all moppr with b->moppr,mopsum with b->mopsum
replace all unpr with b->unpr,unsum with b->unsum
replace all naspr with b->naspr,nassum with b->nassum
replace all molpr with b->molpr,molsum with b->molsum
replace all hlpr with b->hlpr,hlsum with b->hlsum
replace all podpr with b->podpr,podsup with b->podsup

replace all rashod with b->rashod,surash with b->surash
replace all raspod with b->raspod,surpod with b->surpod
replace all rpodg with b->rpodg,rpodn with b->rpodn
replace all g1 with b->g1,g2 with b->g2,g3 with b->g3,g4 with b->g4
replace all surpodg with b->surpodg,surpodn with b->surpodn
replace all sg1 with b->sg1,sg2 with b->sg2,sg3 with b->sg3,sg4 with b->sg4
replace all rperg with b->rperg,surperg with b->surperg
replace all rpern with b->rpern,surpern with b->surpern
replace all rhg with b->rhg,shg with b->shg,rhn with b->rhn,shn with b->shn
replace all rdg with b->rdg,srdg with b->srdg,rdn with b->rdn,srdn with b->srdn
replace all vg with b->vg,svg with b->svg,vn with b->vn,svn with b->svn
replace all nedost with b->nedost
go top
pp='  '
return
