replace all p with b->p,c with b->c,q1 with b->q1,q2 with b->q2,q3 with b->q3,c1 with b->c1,c2 with b->c2,c3 with b->c3
go top
replace all rashod with b->rashod,surash with b->surash,ost with b->ost,sua with b->sua,mesprih with b->mesprih,messum with b->messum
go top
replace all orspr with b->orspr,orssup with b->orssup,podpr with b->podpr,podsup with b->podsup,raspod with b->raspod
go top
replace all surpod with b->surpod,rasper with b->rasper,surper with b->surper,hozras with b->hozras,suhozras with b->suhozras
go top
return
